name: draft-release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORGANIZATION_NAME: "nstr1"
  REPO: "capstone"
  PR_NUMBER: ${{ github.event.pull_request.number }}
  DESC: ${{ github.event.pull_request.title  }}
  HEADER: "Accept: application/vnd.github+json"

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Title?
        run: > 
          echo "PR title is: ${{ github.event.pull_request.title}}"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: patch:patch,minor:minor,major:major
          release_branches: master
      - name: Create a release draft and get its URL
        run: >
          echo "URL=$(
          gh api --method POST -H "$HEADER"
          repos/"$ORGANIZATION_NAME"/"$REPO"/releases
          -f tag_name=${{ steps.tag_version.outputs.new_tag }}
          -f target_commitish='master'
          -f name=${{ steps.tag_version.outputs.new_tag }}
          -f body=${{ steps.tag_version.outputs.changelog }}
          -F draft=true
          | jq -r '.html_url')"
          >> $GITHUB_ENV
      - name: Post comment on PR with the release draft URL
        run: >
          gh api --method POST -H "$HEADER"
          /repos/"$ORGANIZATION_NAME"/"$REPO"/issues/"$PR_NUMBER"/comments
          -f body="Release draft URL: $URL"
