name: draft-release
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: >
          gh api --method POST -H "Accept: application/vnd.github+json" 
          /repos/nstr1/capstone/releases 
          -f tag_name='v2.5.1' 
          -f target_commitish='master' 
          -f name='v2.5.1' 
          -f body='Description' 
          -F draft=true 
          -F prerelease=false 
          -F generate_release_notes=false
          
          
          
