name: draft-release

on:
  pull_request:
    types:
      - closed

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          DESC: ${{ github.event.head_commit.message }}
          ORGANIZATION_NAME: "nstr1"
          REPO: "capstone"
          HEADER: "Accept: application/vnd.github+json"
          TAG: 'v.0.72.1'
      - run: >
          url=$( gh api --method POST -H $HEADER
          /repos/$ORGANIZATION_NAME/$REPO/releases 
          -f tag_name=$TAG
          -f target_commitish='master' 
          -f name=$TAG
          -f body=$DESC
          -F draft=true 
          -F prerelease=false 
          -F generate_release_notes=false
          | jq '.url')
          echo "URL=$url" >> "$GITHUB_ENV"
      - run: >
          gh api --method POST -H $HEADER
          /repos/$ORGANIZATION_NAME/$REPO/issues/$PR_NUMBER/comments 
          -f body=$URL
