name: draft-release

on:
  push:
    branches:
      - master
  
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  DESC: ${{ github.event.pull_request.title }}
  ORGANIZATION_NAME: "nstr1"
  REPO: "capstone"
  HEADER: "Accept: application/vnd.github+json"
  TAG: 'v.0.82.5'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create a release draft and get its url
        run: >
          echo "URL=$( gh api --method POST -H "$HEADER"
          repos/"$ORGANIZATION_NAME"/"$REPO"/releases
          -f tag_name="$TAG"
          -f target_commitish='master'
          -f name="$TAG"
          -f body="$DESC"
          -F draft=true
          | jq -r '.html_url')" >> $GITHUB_ENV
      - name: Post comment on PR with the release draft URL
        run: >
          gh api --method POST -H "$HEADER"
          /repos/"$ORGANIZATION_NAME"/"$REPO"/issues"/$PR_NUMBER"/comments
          -f body="Release draft URL: $URL"


# url=$( gh api \
# --method POST \
# -H "Accept: application/vnd.github+json" \
# /repos/nstr1/capstone/releases \
# -f tag_name='0.73.0' \
# -f target_commitish='master' \
# -f name='0.73.0' \
# -f body='desc' \
# -F draft=true | jq '.html_url')