name: draft-release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
      
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  DESC: ${{ github.event.pull_request.title  }}
  ORGANIZATION_NAME: "nstr1"
  REPO: "capstone"
  HEADER: "Accept: application/vnd.github+json"
  TAG: 'v.0.85.0'

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Get latest release verison
        run: >
          echo "CURRENT_VER=$(
          gh api -H "$HEADER"
          /repos/"$ORGANIZATION_NAME"/"$REPO"/releases/latest)"
          >> $GITHUB_ENV
      - name: echo
        run: 
          echo "$CURRENT_VER"
      - name: Create a release draft and get its URL
        run: >
          echo "URL=$(
          gh api --method POST -H "$HEADER"
          repos/"$ORGANIZATION_NAME"/"$REPO"/releases
          -f tag_name="$TAG"
          -f target_commitish='master'
          -f name="$TAG"
          -f body="$DESC"
          -F draft=true
          | jq -r '.html_url')"
          >> $GITHUB_ENV
      - name: Post comment on PR with the release draft URL
        run: >
          gh api --method POST -H "$HEADER"
          /repos/"$ORGANIZATION_NAME"/"$REPO"/issues/"$PR_NUMBER"/comments
          -f body="Release draft URL: $URL"
