name: draft-release

on:
  pull_request:
    types:
      - closed
  
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  DESC: ${{ github.event.head_commit.message }}
  ORGANIZATION_NAME: "nstr1"
  REPO: "capstone"
  HEADER: "Accept: application/vnd.github+json"
  TAG: 'v.0.72.2'

jobs:
  draft-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - run: >
          echo "URL=$( gh api --method POST -H "$HEADER"
          repos/"$ORGANIZATION_NAME"/"$REPO"/releases
          -f tag_name="$TAG"
          -f target_commitish='master'
          -f name="$TAG"
          -f body="desc"
          -F draft=true
          | jq '.html_url')" >> $GITHUB_ENV
      - name: Post comment on PR with the draft release URL
        run: >
          gh api --method POST -H "$HEADER"
          /repos/"$ORGANIZATION_NAME"/"$REPO"/issues"/$PR_NUMBER"/comments
          -f body="$URL"


# url=$( gh api \
# --method POST \
# -H "Accept: application/vnd.github+json" \
# /repos/nstr1/capstone/releases \
# -f tag_name='0.73.0' \
# -f target_commitish='master' \
# -f name='0.73.0' \
# -f body='desc' \
# -F draft=true | jq '.html_url')